[package]
name = "nb"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version="4.5.16"}
confy = {version="0.6.1"}
dirs = "5.0.1"
serde = {version="1.0.209", features=["derive"]}
thiserror = "1.0.63"
